#!/bin/bash
cd <REPLACE_WITH_CHECKOUT_PATH>
source venv/bin/activate
export SPOTIFY_CLIENT_ID=<REPLACE_WITH_SPOTIFY_CLIENT_ID>
export SPOTIFY_CLIENT_SECRET=<REPLACE_WITH_SPOTIFY_CLIENT_SECRET>
export SPOTIFY_PLAYLIST=<REPLACE_WITH_SPOTIFY_PLAYLIST_ID>
python3 main.py